# Site settings
name: Sonu Sanjeev
email: sonu.etm.com
#canonical_url: https://edwinexemplar.com
keywords: "Android Engineer, Kotlin, Java, Jepack libraries, Retrofit, OkHttp, Dagger, Mockito, Gradle"
skills: "Senior Android Developer in Bangalore, India (@Harman)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sonusanjeev/
  - title: medium
    url: https://sonu-sanjeev.medium.com/
  - title: twitter
    url: https://twitter.com/sonusanjeev_
  - title: stack - overflow
    url: https://stackoverflow.com/users/8878425/sonu-sanjeev?tab=profile  
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
